{% set version = "01.3" %}
{% set sha256 = "d9b026a3090c7d27334766dbcc1cc9957fd3e9eb7de7e94bd8578ec0db4af701" %}

package:
  name: guide-counter
  version: {{ version }}

source:
  url: https://github.com/fulcrumgenomics/guide-counter/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - rust >=1.56
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - guide-counter --help

about:
  home: https://github.com/fulcrumgenomics/guide-counter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fast and accurate guide counting for CRISPR screens
