{% set version = "2.12.2" %}

package:
  name: tiddit
  version: '{{ version }}'

source:
  url: https://github.com/SciLifeLab/TIDDIT/archive/TIDDIT-{{ version }}.tar.gz
  sha256: 679d06769077afb0431dfb780f2a7d3311c0d9c389301dcf55ab46ee360d91df
  patches:
    - TIDDIT.py.patch

build:
  number: 1
  skip: True  # [osx]

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - cmake
    - python
    - cython
  host:
    - python
    - cython
    - numpy
    - pip
    - bwa
    - ropebwt2

  run:
    - python
    - numpy
    - pysam
    - samtools
    - fermi2
    - bwa
    - ropebwt2

test:
  commands:
    - TIDDIT
    - TIDDIT.py
    - tiddit --help
    - fermi2 2>&1 | grep "^Usage:"
    - ropebwt2 -h /dev/null 2>&1 | grep ropebwt2
    - bwa 2>&1 | grep "index sequences in the"

about:
  home: https://github.com/SciLifeLab/TIDDIT
  license: GPL-3.0-only
  license_file: LICENSE
  summary: "TIDDIT - structural variant calling."
